"""Initial seed data for 25 books."""


def get_initial_books():
    """Return the initial 25 books dataset."""
    return {
        1: {
            "id": 1,
            "name": "The Russian",
            "author": "James Patterson",
            "type": "fiction",
            "price": 12.99,
            "current-stock": 12,
            "available": True,
        },
        2: {
            "id": 2,
            "name": "Just as I Am",
            "author": "Cicely Tyson",
            "type": "non-fiction",
            "price": 15.50,
            "current-stock": 8,
            "available": True,
        },
        3: {
            "id": 3,
            "name": "The Vanishing Half",
            "author": "Brit Bennett",
            "type": "fiction",
            "price": 9.99,
            "current-stock": 0,
            "available": False,
        },
        4: {
            "id": 4,
            "name": "Untamed",
            "author": "Glennon Doyle",
            "type": "non-fiction",
            "price": 14.00,
            "current-stock": 5,
            "available": True,
        },
        5: {
            "id": 5,
            "name": "Viscount Who Loved Me",
            "author": "Julia Quinn",
            "type": "fiction",
            "price": 11.50,
            "current-stock": 15,
            "available": True,
        },
        6: {
            "id": 6,
            "name": "Think Again",
            "author": "Adam Grant",
            "type": "non-fiction",
            "price": 18.00,
            "current-stock": 10,
            "available": True,
        },
        7: {
            "id": 7,
            "name": "The Midnight Library",
            "author": "Matt Haig",
            "type": "fiction",
            "price": 13.50,
            "current-stock": 7,
            "available": True,
        },
        8: {
            "id": 8,
            "name": "Atomic Habits",
            "author": "James Clear",
            "type": "non-fiction",
            "price": 16.99,
            "current-stock": 20,
            "available": True,
        },
        9: {
            "id": 9,
            "name": "The Invisible Life of Addie LaRue",
            "author": "V.E. Schwab",
            "type": "fiction",
            "price": 10.99,
            "current-stock": 3,
            "available": True,
        },
        10: {
            "id": 10,
            "name": "Greenlights",
            "author": "Matthew McConaughey",
            "type": "non-fiction",
            "price": 19.99,
            "current-stock": 6,
            "available": True,
        },
        11: {
            "id": 11,
            "name": "The Four Winds",
            "author": "Kristin Hannah",
            "type": "fiction",
            "price": 14.99,
            "current-stock": 9,
            "available": True,
        },
        12: {
            "id": 12,
            "name": "Caste",
            "author": "Isabel Wilkerson",
            "type": "non-fiction",
            "price": 22.00,
            "current-stock": 4,
            "available": True,
        },
        13: {
            "id": 13,
            "name": "Klara and the Sun",
            "author": "Kazuo Ishiguro",
            "type": "fiction",
            "price": 13.99,
            "current-stock": 11,
            "available": True,
        },
        14: {
            "id": 14,
            "name": "The Body Keeps the Score",
            "author": "Bessel van der Kolk",
            "type": "non-fiction",
            "price": 17.50,
            "current-stock": 14,
            "available": True,
        },
        15: {
            "id": 15,
            "name": "Project Hail Mary",
            "author": "Andy Weir",
            "type": "fiction",
            "price": 15.99,
            "current-stock": 18,
            "available": True,
        },
        16: {
            "id": 16,
            "name": "Sapiens",
            "author": "Yuval Noah Harari",
            "type": "non-fiction",
            "price": 20.00,
            "current-stock": 2,
            "available": True,
        },
        17: {
            "id": 17,
            "name": "The Maid",
            "author": "Nita Prose",
            "type": "fiction",
            "price": 11.99,
            "current-stock": 6,
            "available": True,
        },
        18: {
            "id": 18,
            "name": "Educated",
            "author": "Tara Westover",
            "type": "non-fiction",
            "price": 14.50,
            "current-stock": 13,
            "available": True,
        },
        19: {
            "id": 19,
            "name": "Beautiful World Where Are You",
            "author": "Sally Rooney",
            "type": "fiction",
            "price": 12.50,
            "current-stock": 8,
            "available": True,
        },
        20: {
            "id": 20,
            "name": "The Power of Now",
            "author": "Eckhart Tolle",
            "type": "non-fiction",
            "price": 11.00,
            "current-stock": 16,
            "available": True,
        },
        21: {
            "id": 21,
            "name": "The Silent Patient",
            "author": "Alex Michaelides",
            "type": "fiction",
            "price": 10.50,
            "current-stock": 5,
            "available": True,
        },
        22: {
            "id": 22,
            "name": "Deep Work",
            "author": "Cal Newport",
            "type": "non-fiction",
            "price": 15.00,
            "current-stock": 9,
            "available": True,
        },
        23: {
            "id": 23,
            "name": "Where the Crawdads Sing",
            "author": "Delia Owens",
            "type": "fiction",
            "price": 13.00,
            "current-stock": 7,
            "available": True,
        },
        24: {
            "id": 24,
            "name": "Becoming",
            "author": "Michelle Obama",
            "type": "non-fiction",
            "price": 18.50,
            "current-stock": 11,
            "available": True,
        },
        25: {
            "id": 25,
            "name": "The Alchemist",
            "author": "Paulo Coelho",
            "type": "fiction",
            "price": 9.50,
            "current-stock": 25,
            "available": True,
        },
    }
